# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storage/
    - sdk/eng/
    
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/storage/
    - sdk/eng/

resources:
  repositories:
  - repository: SwiftPM-AzureStorageBlob
    type: github
    name: Azure/SwiftPM-AzureStorageBlob
    endpoint: Azure

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: storage
    Artifacts:
    - name: AzureStorageBlob
