# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/communication/
    - sdk/eng/
    
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/communication/
    - sdk/eng/


extends:
  template: templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: communication
    Artifacts:
    - name: AzureCommunicationCommon
    - name: AzureCommunicationChat
    - name: AzureCommunicationCalling
