parameters:
  BuildScheme: all # Build all projects by default

jobs:
  - job: 'Build'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: '$(OSVmImage)'

    steps:
      - script: |
          echo "##vso[build.addbuildtag]Scheduled"
        displayName: 'Tag scheduled builds'
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'],'master'),eq(variables['Build.Reason'],'Schedule'))

      - template: /eng/common/pipelines/templates/steps/daily-dev-build-variable.yml

      - script: sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app
        displayName: 'Use Xcode $(XcodeVersion)'

      - script: pod install
        displayName: 'Install dependencies'

      - script: |
          set -o pipefail
          xcodebuild -workspace AzureSDK.xcworkspace \
                     -scheme ${{parameters.BuildScheme}} \
                     -destination "platform=iOS Simulator,OS=$(SimulatorVersion),name=$(SimulatorDevice)" \
                     -configuration Release \
                     -derivedDataPath $(Build.ArtifactStagingDirectory) \
                     build | xcpretty -c
        displayName: 'Build libraries for release'

      - publish: $(Build.ArtifactStagingDirectory)/Build/Products/Release-iphonesimulator
        displayName: 'Publish release artifacts [iphonesimulator]'
        artifact: 'bundles-release-iphonesimulator'

  - job: 'Analyze'
    condition: and(succeeded(), ne(variables['Skip.Analyze'], 'true'))

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: '$(OSVmImage)'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.6'
        inputs:
          versionSpec: '3.6'

      - script: sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app
        displayName: 'Use Xcode $(XcodeVersion)'

      - template: ../../../common/pipelines/templates/steps/verify-links.yml
        parameters:
          Directory: ""
          CheckLinkGuidance: $true
          
      - script: |
          brew install swiftlint
          case "${{parameters.BuildScheme}}" in
            all)
              swiftlint lint --path . --quiet --reporter emoji
              ;;
            sdk|examples)
              swiftlint lint --path ${{parameters.BuildScheme}} --quiet --reporter emoji
              ;;
            *)
              swiftlint lint --path sdk/${{parameters.BuildScheme}} --quiet --reporter emoji
              ;;
          esac
        displayName: 'Lint sources'

      - script: |
          pip install setuptools wheel
          pip install doc-warden==$(DocWardenVersion)
          ward scan -d $(Build.SourcesDirectory) -c $(Build.SourcesDirectory)/eng/.docsettings.yml
        displayName: 'Verify readmes'

      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        # ComponentGovernance is currently unable to run on pull requests of public projects. Running on non-PR
        # builds should be sufficient.
        condition: and(succeededOrFailed(), ne(variables['Build.Reason'], 'PullRequest'))
        displayName: 'Component detection'

  - job: 'UnitTest'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: '$(OSVmImage)'

    steps:
      - script: sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app
        displayName: 'Use Xcode $(XcodeVersion)'

      - script: gem install -N trainer slather -- --use-system-libraries
        displayName: 'Install build tools'

      - script: pod install
        displayName: 'Install dependencies'

      - script: |
          set -o pipefail
          xcodebuild -workspace AzureSDK.xcworkspace \
                     -scheme ${{parameters.BuildScheme}} \
                     -destination "platform=iOS Simulator,OS=$(SimulatorVersion),name=$(SimulatorDevice)" \
                     -configuration Debug \
                     -derivedDataPath $(Build.ArtifactStagingDirectory) \
                     -enableCodeCoverage YES \
                     test | xcpretty -c
        displayName: 'Build and test libraries'

      - publish: $(Build.ArtifactStagingDirectory)/Logs/Test
        displayName: 'Preserve logs on failure'
        artifact: 'test-failure-logs'
        condition: failed()

      - script: trainer --path $(Build.ArtifactStagingDirectory) --fail_build false
        env:
          FASTLANE_OPT_OUT_USAGE: true
        displayName: 'Convert unit test results'

      - task: PublishTestResults@2
        inputs:
          searchFolder: '$(Build.ArtifactStagingDirectory)/Logs/Test'
          testResultsFiles: '*.xml'
          testRunTitle: 'Unit Tests - [Xcode $(XcodeVersion), iOS $(SimulatorVersion)]'
        displayName: 'Publish unit test results'

      - script: |
          echo "Getting list of projects in scheme ${{parameters.BuildScheme}}"
          xcodebuild -showBuildSettings \
                     -workspace AzureSDK.xcworkspace \
                     -scheme ${{parameters.BuildScheme}} \
                     -configuration Debug \
          | grep PROJECT_FILE_PATH \
          | awk -F ' = ' '{print $NF}' \
          | while read PROJECT_PATH; do
              PROJECT_NAME=$(echo $PROJECT_PATH | awk -F/ '{print $NF}' | sed 's/.xcodeproj//')
              echo "Generating reports for $PROJECT_NAME"
              slather coverage -x \
                              --workspace AzureSDK.xcworkspace \
                              --scheme ${{parameters.BuildScheme}} \
                              --configuration Debug \
                              --binary-basename $PROJECT_NAME \
                              --build-directory $(Build.ArtifactStagingDirectory) \
                              --output-directory $(Build.ArtifactStagingDirectory)/reports/$PROJECT_NAME \
                              $PROJECT_PATH
            done
        displayName: 'Generate code coverage reports'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(Build.ArtifactStagingDirectory)/reports/*/*.xml'
        displayName: 'Publish code coverage'
