resources:
  repositories:
  - repository: azure-sdk-build-tools
    type: git
    name: internal/azure-sdk-build-tools
    ref: refs/heads/feature/engsys-ios-barebones
  - repository: azure-sdk-tools
    type: github
    name: Azure/azure-sdk-tools
    endpoint: azure
trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/core/
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/core/
stages:
- template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: core
    Artifacts:
    - name: AzureCore
      safeName: azurecore
