parameters:
- name: BuildScheme
  type: string
  default: sdk
- name: ServiceDirectory
  type: string

stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        BuildScheme: ${{parameters.BuildScheme}}
