parameters:
- name: BuildScheme
  type: string
  default: all
  
stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        BuildScheme: ${{parameters.BuildScheme}}
